version: "3"

volumes:
  django_db_dev: {}

services:
  web:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
    networks:
      - djangonetwork
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - django_db_dev:/var/lib/postgresql/data
    networks:
      - djangonetwork
  networks:
    djangonetwork:
        driver: bridge