# Generated by Django 3.2.5 on 2021-07-12 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210712_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date created'),
        ),
    ]
